### ISSUE TITLE
Fix documentation for python wrapper and state vector

### ISSUE THREAD

**Issue by arghdos** [SLACKHA/pyJac#15]
It's clear that having the Temperature be the first value in the state vector is causing confusion for new users (e.g. #14).  We need to document both the expected structure of the state vector for (C/CUDA) and the python interface

**Comment by arghdos** [comment]
WIP: added more [documentation](http://slackha.github.io/pyJac/faqs.html) and [examples](http://slackha.github.io/pyJac/examples.html).

@michael-a-hansen I'd also be interested in your feedback, to see if that explains things a bit more

**Comment by michael-a-hansen** [comment]
Looks good to me :)

**Comment by arghdos** [comment]
Ok, I'm going to close it then!  If there are any more examples you need please let us know!
