### ISSUE TITLE
Performance tester -nt switch

### ISSUE THREAD

**Issue by ndeak** [SLACKHA/pyJac#19]
Hello,

I noticed while running some of the example commands in the documentation that there is a minor issue with the pyjac.performance_tester function. In the example provided, it indicates that this function has a -nt switch for the number of threads, but this functionality does not appear to be present in the version I pulled down which seems to be the latest version available. Figured I would bring this to your attention so the example can be updated, or the functionality can be added.

Thanks,
Nick

**Comment by arghdos** [comment]
@ndeak thanks for the report, you're correct that's a bug in the example provided.  It looks like the performance tester will automatically test pyJac with varying #'s of threads (incremented by powers of 2)

This should be addressed w/ commits 8179087 & 4c5ec24
