### ISSUE TITLE
Code doesn't provide info about last species

### ISSUE THREAD

**Issue by kyleniemeyer** [SLACKHA/pyJac#22]
From @stonecp:

Right now info about the last species is given at Jacobian generation, but not after that. It would be useful to put info about this in the header, and perhaps some functions about getting the name or previous position.

**Comment by arghdos** [comment]
@stonecp @kyleniemeyer 

I believe the species list is written to the `mechanism.h` header (or the like)
https://github.com/SLACKHA/pyJac/blob/master/pyjac/core/mech_auxiliary.py#L139

But we could turn this into a function like Cantera's species names / species indicies
