### ISSUE TITLE
v2.0: add option for constant volume assumption

### ISSUE THREAD

**Issue by kyleniemeyer** [SLACKHA/pyJac#4]
This isn't necessary for the initial release, but for v2.0 it would be good to add the option to do everything assuming constant volume, rather than only constant pressure as is currently the case.

This would be useful for internal combustion (e.g, reciprocating engine) simulations, in particular.

**Comment by haowu80s** [comment]
This is a rather important issue.
When using these tool for CFD simulation with operator splitting, whether to use constant pressure or constant volume depends on if we are solving energy or enthalpy equation. The choice of using energy equation is particularly popular for compressible solver as it is conservative. Thus, constant volume is desired.

**Comment by arghdos** [comment]
Hi, we are currently developing a new set of equations that will result in a sparse Jacobian (and will therefore benefit from sparse linear algebra methods).  This will include a constant volume option

**Comment by haowu80s** [comment]
Hi,
Any plan on how soon the new development will be releases?

**Comment by arghdos** [comment]
@haowu80s 

The beta should be released within the next few months, with the paper following shortly after

**Comment by kahilah** [comment]
Hi,

Any updates regarding the status/release of the sparse formulation? Keep up the good work :) !

**Comment by arghdos** [comment]
@kahilah 

It's still "on the way".  We presented our progress at the NCM a few months ago, and I've uploaded the presentation to [figshare](https://figshare.com/articles/SIMD-Acceleration_of_Chemical_Source_Term_Evaluation_via_Python/4962662) if you'd like to take a look!

**Comment by kyleniemeyer** [comment]
Hi @kahilah, if you are interested, we just created a Groups.io-based user group for the SLACKHA project, which includes pyJac: https://groups.io/g/slackha-users (I would invite you directly, but don't know your email)

**Comment by kyleniemeyer** [comment]
@kahilah scratch that, I found a prior email from you!

**Comment by kahilah** [comment]
Thanks for the slides and invitation to the group. User-group is a good idea!
